music_directory "/home/cheshire/Music"
playlist_directory "/home/cheshire/.local/share/mpd/playlist"

db_file "/home/cheshire/.local/share/mpd/database"
state_file "/home/cheshire/.local/state/mpd/state"
sticker_file "/home/cheshire/.local/share/mpd/sticker.sql"

auto_update "yes"

audio_output {
    type "pipewire"
    name "PipeWire audio_output"
    target "alsa_output.usb-iFi__by_AMR__iFi__by_AMR__HD_USB_Audio_0002-00.pro-output-0"
}
