import = ["/home/cheshire/.config/alacritty/themes/themes/breeze.toml"]

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Light"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "LightItalic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "ExtraLightItalic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "ExtraLight"

[shell]
program = "/bin/fish"
