[terminal.shell]
program = "/bin/fish"

[window]
opacity = 0.7
blur = true

[general]
import = ["/home/cheshire/.config/alacritty/themes/catppuccin-mocha.toml",
    "/home/cheshire/.config/alacritty/fonts.toml"]

