# abrt-action-analyze-java
# Autogenerated from man page /usr/share/man/man1/abrt-action-analyze-java.1.gz
complete -c abrt-action-analyze-java -s d -d 'Path to a problem directory'
complete -c abrt-action-analyze-java -s f -d 'Path to a stack trace'
complete -c abrt-action-analyze-java -s o -d 'Print the result to stdout'
complete -c abrt-action-analyze-java -s v -d 'Be more verbose.  Can be given multiple times'

