# catimg
# Autogenerated from man page /usr/share/man/man1/catimg.1.gz
complete -c catimg -s c -d 'Coerce colors to a restricted palette'
complete -c catimg -s h -d 'Prints a help message'
complete -c catimg -s H -d 'Specify the height of the displayed image, passing \'0\' will use terminal heig…'
complete -c catimg -s l -d 'Specify the amount of loops that catimg should repeat a GIF'
complete -c catimg -s r -d 'Possible values 1 or 2.  Force the resolution of the image'
complete -c catimg -s t -d 'Disables true color (24-bit) support, falling back to 256 color escape codes …'
complete -c catimg -s w -d 'Specify the width of the displayed image'

