# fros
# Autogenerated from man page /usr/share/man/man1/fros.1.gz
complete -c fros -s h -l help -d 'show help message and exit'
complete -c fros -s v -l verbose -d 'makes the output more verbose/talkative'
complete -c fros -l is-available -d 'check if the current environment supports screencasting (0: is available, 1: …'

