# toolbox-enter
# Autogenerated from man page /usr/share/man/man1/toolbox-enter.1.gz
complete -c toolbox-enter -l distro -s d -d 'Enter a toolbox container for a different operating system DISTRO than the ho…'
complete -c toolbox-enter -l release -s r -d 'Enter a toolbox container for a different operating system RELEASE than the h…'

