# toolbox-init-container
# Autogenerated from man page /usr/share/man/man1/toolbox-init-container.1.gz
complete -c toolbox-init-container -l gid -d 'Pass GID as the user\'s numerical group ID from the host to the toolbox contai…'
complete -c toolbox-init-container -l home -d 'Create a user inside the toolbox container whose login directory is HOME'
complete -c toolbox-init-container -l home-link -d 'Make /home a symbolic link to /var/home'
complete -c toolbox-init-container -l media-link -d 'Make /media a symbolic link to /run/media'
complete -c toolbox-init-container -l mnt-link -d 'Make /mnt a symbolic link to /var/mnt'
complete -c toolbox-init-container -l monitor-host -d 'Ensures that certain configuration files inside the toolbox container are kep…'
complete -c toolbox-init-container -l shell -d 'Create a user inside the toolbox container whose login shell is SHELL'
complete -c toolbox-init-container -l uid -d 'Create a user inside the toolbox container whose numerical user ID is UID'
complete -c toolbox-init-container -l user -d 'Create a user inside the toolbox container whose login name is LOGIN'

