# toolbox-create
# Autogenerated from man page /usr/share/man/man1/toolbox-create.1.gz
complete -c toolbox-create -l authfile -d 'Path to a FILE with credentials for authenticating to the registry for privat…'
complete -c toolbox-create -l distro -s d -d 'Create a toolbox container for a different operating system DISTRO than the h…'
complete -c toolbox-create -l image -s i -d 'Change the NAME of the image used to create the toolbox container'
complete -c toolbox-create -l release -d 'If NAME does not contain a registry, the local image storage will be consulte…'
complete -c toolbox-create -s r -d 'Create a toolbox container for a different operating system RELEASE than the …'

