# toolbox-list
# Autogenerated from man page /usr/share/man/man1/toolbox-list.1.gz
complete -c toolbox-list -l containers -s c -d 'List only toolbox containers, not images'
complete -c toolbox-list -l images -s i -d 'List only toolbox images, not containers'

