# toolbox-rmi
# Autogenerated from man page /usr/share/man/man1/toolbox-rmi.1.gz
complete -c toolbox-rmi -l all -s a -d 'Remove all toolbox images'
complete -c toolbox-rmi -l force -s f -d 'Force the removal of toolbox images that are used by toolbox containers'

