# toolbox-rm
# Autogenerated from man page /usr/share/man/man1/toolbox-rm.1.gz
complete -c toolbox-rm -l all -s a -d 'Remove all toolbox containers'
complete -c toolbox-rm -l force -s f -d 'Force the removal of running and paused toolbox containers'

