# toolbox-run
# Autogenerated from man page /usr/share/man/man1/toolbox-run.1.gz
complete -c toolbox-run -l container -d 'A toolbox container is an OCI container'
complete -c toolbox-run -s c -d 'Run command inside a toolbox container with the given NAME'
complete -c toolbox-run -l distro -s d -d 'Run command inside a toolbox container for a different operating system DISTR…'
complete -c toolbox-run -l preserve-fds -d 'Pass down to command N additional file descriptors (in addition to 0, 1, 2)'
complete -c toolbox-run -l release -s r -d 'Run command inside a toolbox container for a different operating system RELEA…'

