# toolbox
# Autogenerated from man page /usr/share/man/man1/toolbox.1.gz
complete -c toolbox -l distro -l release -d 'specifies its version.  Supported combinations are: rhel	<major>. <minor> eg'
complete -c toolbox -l assumeyes -s y -d 'Automatically answer yes for all questions'
complete -c toolbox -l help -s h -d 'Print a synopsis of this manual and exit'
complete -c toolbox -l log-level -d 'Log messages above specified level: debug, info, warn, error, fatal or panic …'
complete -c toolbox -l log-podman -d 'Show log messages of invocations of Podman based on the logging level specifi…'
complete -c toolbox -l verbose -s v -d 'Same as --log-level=debug.  Use -vv to include --log-podman'

