# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#1e1e2e'
foreground='#cdd6f4'
cursor='#f5e0dc'

# Colors
color0='#45475a'
color1='#f38ba8'
color2='#a6e3a1'
color3='#f9e2af'
color4='#89b4fa'
color5='#f5c2e7'
color6='#94e2d5'
color7='#bac2de'
color8='#585b70'
color9='#f38ba8'
color10='#a6e3a1'
color11='#f9e2af'
color12='#89b4fa'
color13='#f5c2e7'
color14='#94e2d5'
color15='#a6adc8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
