[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#cdd6f4"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#cdd6f4"

[colors.search.matches]
foreground = "#45475a"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#585b70"
background = "#bac2de"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#a6adc8"
red = "#f38ba8"
green = "#f5c2e7"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#a6e3a1"
cyan = "#94e2d5"
white = "#585b70"

