# vim:fileencoding=utf-8:foldmethod=marker

include theme.conf
include keybinds.conf

# font_family      JetBrainsMonoNerdFont-Light
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

font_size 13.0
disable_ligatures never

cursor_shape underline
cursor_blink_interval -1

scrollback_lines 2000
scrollbar scrolled
scrollbar_interactive yes

mouse_hide_wait 1.0

enable_audio_bell no

background_opacity 0.8

shell fish
editor bob run nightly

shell_integration no-cursor
# BEGIN_KITTY_FONTS
font_family      family='Iosevka Nerd Font Mono' postscript_name=IosevkaNFM-Light
bold_font        family='Iosevka Nerd Font Mono' postscript_name=IosevkaNFM
italic_font      family='Iosevka Nerd Font Mono' postscript_name=IosevkaNFM-LightItalic
bold_italic_font auto
# END_KITTY_FONTS
